// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QBCA.Data;

#nullable disable

namespace CNPM_QBCA.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250630031337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CNPM_QBCA.Models.MockExam", b =>
                {
                    b.Property<int>("MockExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MockExamID"));

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssignmentID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LecturerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MockExamID");

                    b.HasIndex("AssignmentID");

                    b.ToTable("MockExam");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.MockExamAnswer", b =>
                {
                    b.Property<int>("MockExamAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MockExamAnswerID"));

                    b.Property<string>("AnswerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MockExamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MockExamAnswerID");

                    b.HasIndex("MockExamId");

                    b.ToTable("MockExamAnswer");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.MockFeedback", b =>
                {
                    b.Property<int>("MockFeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MockFeedbackID"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FeedbackDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MockExamId")
                        .HasColumnType("int");

                    b.HasKey("MockFeedbackID");

                    b.HasIndex("MockExamId");

                    b.ToTable("MockFeedback");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.MockQuestion", b =>
                {
                    b.Property<int>("MockQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MockQuestionID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MockExamId")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MockQuestionID");

                    b.HasIndex("MockExamId");

                    b.ToTable("MockQuestion");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.TaskModel", b =>
                {
                    b.Property<int>("TaskModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskModelId"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistributionID")
                        .HasColumnType("int");

                    b.Property<int?>("ExamPlanID")
                        .HasColumnType("int");

                    b.Property<int?>("ExamReviewID")
                        .HasColumnType("int");

                    b.Property<int?>("FeedbackID")
                        .HasColumnType("int");

                    b.Property<int?>("MockExamID")
                        .HasColumnType("int");

                    b.Property<int?>("NotificationID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskModelId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DistributionID");

                    b.HasIndex("ExamPlanID");

                    b.HasIndex("ExamReviewID");

                    b.HasIndex("FeedbackID");

                    b.HasIndex("MockExamID");

                    b.HasIndex("NotificationID");

                    b.ToTable("TaskModels");
                });

            modelBuilder.Entity("QBCA.Models.AssignedPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AssignedByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedToID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistributionID")
                        .HasColumnType("int");

                    b.Property<int>("ExamPlanID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AssignedByID");

                    b.HasIndex("AssignedToID");

                    b.HasIndex("DistributionID");

                    b.HasIndex("ExamPlanID");

                    b.ToTable("AssignPlans");
                });

            modelBuilder.Entity("QBCA.Models.CLO", b =>
                {
                    b.Property<int>("CLOID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CLOID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("CLOID");

                    b.HasIndex("SubjectID");

                    b.ToTable("CLOs");
                });

            modelBuilder.Entity("QBCA.Models.DifficultyLevel", b =>
                {
                    b.Property<int>("DifficultyLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DifficultyLevelID"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("DifficultyLevelID");

                    b.HasIndex("SubjectID");

                    b.ToTable("DifficultyLevels");
                });

            modelBuilder.Entity("QBCA.Models.DuplicateCheckResult", b =>
                {
                    b.Property<int>("CheckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckID"));

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("SimilarQuestionID")
                        .HasColumnType("int");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("float");

                    b.HasKey("CheckID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SimilarQuestionID");

                    b.ToTable("DuplicateCheckResults");
                });

            modelBuilder.Entity("QBCA.Models.Exam", b =>
                {
                    b.Property<int>("ExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DistributionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamPlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmittedBy")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExamID");

                    b.HasIndex("DistributionID")
                        .IsUnique();

                    b.HasIndex("SubmittedBy");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("QBCA.Models.ExamApproveTask", b =>
                {
                    b.Property<int>("ExamApproveTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamApproveTaskID"));

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedToUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<int?>("ExamID1")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFinalVersion")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ExamApproveTaskID");

                    b.HasIndex("AssignedByUserID");

                    b.HasIndex("AssignedToUserID");

                    b.HasIndex("ExamID");

                    b.HasIndex("ExamID1");

                    b.HasIndex("UserID");

                    b.ToTable("ExamApproveTasks");
                });

            modelBuilder.Entity("QBCA.Models.ExamPlan", b =>
                {
                    b.Property<int>("ExamPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamPlanID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExamPlanID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SubjectID");

                    b.ToTable("ExamPlans");
                });

            modelBuilder.Entity("QBCA.Models.ExamPlanDistribution", b =>
                {
                    b.Property<int>("DistributionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributionID"));

                    b.Property<int?>("AssignedManagerRoleID")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevelID")
                        .HasColumnType("int");

                    b.Property<int>("ExamPlanID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfQuestions")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Assigned");

                    b.HasKey("DistributionID");

                    b.HasIndex("AssignedManagerRoleID");

                    b.HasIndex("DifficultyLevelID");

                    b.HasIndex("ExamPlanID");

                    b.ToTable("ExamPlanDistributions");
                });

            modelBuilder.Entity("QBCA.Models.ExamQuestion", b =>
                {
                    b.Property<int>("ExamQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamQuestionID"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<int>("ExamPlanID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ExamQuestionID");

                    b.HasIndex("ExamID");

                    b.HasIndex("ExamPlanID");

                    b.HasIndex("QuestionID");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("QBCA.Models.ExamReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("ExamQuestionID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewResult")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("ExamQuestionID");

                    b.HasIndex("ReviewerID");

                    b.ToTable("ExamReviews");
                });

            modelBuilder.Entity("QBCA.Models.Login", b =>
                {
                    b.Property<int>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LoginID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("QBCA.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedEntityID")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("QBCA.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int>("CLOID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevelID")
                        .HasColumnType("int");

                    b.Property<int?>("ExamPlanDistributionDistributionID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int?>("SubmissionID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("CLOID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DifficultyLevelID");

                    b.HasIndex("ExamPlanDistributionDistributionID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("SubmissionID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QBCA.Models.ReviewExam", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistributionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamPlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.HasIndex("DistributionID");

                    b.HasIndex("ExamPlanID");

                    b.HasIndex("ReviewerID");

                    b.ToTable("ReviewExams");
                });

            modelBuilder.Entity("QBCA.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RoleName");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("QBCA.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("QBCA.Models.SubmissionApproval", b =>
                {
                    b.Property<int>("SubmissionApprovalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionApprovalID"));

                    b.Property<int>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedPlanID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubmissionTableID")
                        .HasColumnType("int");

                    b.HasKey("SubmissionApprovalID");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("AssignedPlanID");

                    b.HasIndex("SubmissionTableID");

                    b.ToTable("SubmissionApprovals");
                });

            modelBuilder.Entity("QBCA.Models.SubmissionTable", b =>
                {
                    b.Property<int>("SubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionID"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<double?>("DuplicateRate")
                        .HasColumnType("float");

                    b.Property<string>("DuplicateReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerComment")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubmissionID");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PlanID");

                    b.ToTable("SubmissionTables");
                });

            modelBuilder.Entity("QBCA.Models.TaskAssignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistributionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExamPlanDistributionDistributionID")
                        .HasColumnType("int");

                    b.Property<int>("ExamPlanID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("DistributionID");

                    b.HasIndex("ExamPlanDistributionDistributionID");

                    b.HasIndex("ExamPlanID");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("QBCA.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.MockExam", b =>
                {
                    b.HasOne("QBCA.Models.TaskAssignment", "TaskAssignment")
                        .WithMany()
                        .HasForeignKey("AssignmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.MockExamAnswer", b =>
                {
                    b.HasOne("CNPM_QBCA.Models.MockExam", "MockExam")
                        .WithMany("Answers")
                        .HasForeignKey("MockExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MockExam");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.MockFeedback", b =>
                {
                    b.HasOne("CNPM_QBCA.Models.MockExam", "MockExam")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MockExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MockExam");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.MockQuestion", b =>
                {
                    b.HasOne("CNPM_QBCA.Models.MockExam", "MockExam")
                        .WithMany("Questions")
                        .HasForeignKey("MockExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MockExam");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.TaskModel", b =>
                {
                    b.HasOne("QBCA.Models.User", "Assignee")
                        .WithMany("TasksAssigned")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "Creator")
                        .WithMany("TasksCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlanDistribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QBCA.Models.ExamPlan", "ExamPlan")
                        .WithMany()
                        .HasForeignKey("ExamPlanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QBCA.Models.ExamReview", "ExamReview")
                        .WithMany("Tasks")
                        .HasForeignKey("ExamReviewID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CNPM_QBCA.Models.MockFeedback", "Feedback")
                        .WithMany("Tasks")
                        .HasForeignKey("FeedbackID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CNPM_QBCA.Models.MockExam", "MockExam")
                        .WithMany("Tasks")
                        .HasForeignKey("MockExamID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QBCA.Models.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignee");

                    b.Navigation("Creator");

                    b.Navigation("Distribution");

                    b.Navigation("ExamPlan");

                    b.Navigation("ExamReview");

                    b.Navigation("Feedback");

                    b.Navigation("MockExam");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("QBCA.Models.AssignedPlan", b =>
                {
                    b.HasOne("QBCA.Models.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedByID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlanDistribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlan", "ExamPlan")
                        .WithMany()
                        .HasForeignKey("ExamPlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("AssignedTo");

                    b.Navigation("Distribution");

                    b.Navigation("ExamPlan");
                });

            modelBuilder.Entity("QBCA.Models.CLO", b =>
                {
                    b.HasOne("QBCA.Models.Subject", "Subject")
                        .WithMany("CLOs")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QBCA.Models.DifficultyLevel", b =>
                {
                    b.HasOne("QBCA.Models.Subject", "Subject")
                        .WithMany("DifficultyLevels")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QBCA.Models.DuplicateCheckResult", b =>
                {
                    b.HasOne("QBCA.Models.Question", "Question")
                        .WithMany("DuplicateCheckResults")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.Question", "SimilarQuestion")
                        .WithMany("SimilarQuestions")
                        .HasForeignKey("SimilarQuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SimilarQuestion");
                });

            modelBuilder.Entity("QBCA.Models.Exam", b =>
                {
                    b.HasOne("QBCA.Models.ExamPlanDistribution", "ExamPlanDistribution")
                        .WithOne("Exam")
                        .HasForeignKey("QBCA.Models.Exam", "DistributionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamPlanDistribution");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("QBCA.Models.ExamApproveTask", b =>
                {
                    b.HasOne("QBCA.Models.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QBCA.Models.Exam", null)
                        .WithMany("ApproveTasks")
                        .HasForeignKey("ExamID1");

                    b.HasOne("QBCA.Models.User", null)
                        .WithMany("AssignedTasks")
                        .HasForeignKey("UserID");

                    b.Navigation("AssignedBy");

                    b.Navigation("AssignedTo");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("QBCA.Models.ExamPlan", b =>
                {
                    b.HasOne("QBCA.Models.User", "CreatedByUser")
                        .WithMany("ExamPlansCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QBCA.Models.Subject", "Subject")
                        .WithMany("ExamPlans")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QBCA.Models.ExamPlanDistribution", b =>
                {
                    b.HasOne("QBCA.Models.Role", "AssignedManagerRole")
                        .WithMany()
                        .HasForeignKey("AssignedManagerRoleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QBCA.Models.DifficultyLevel", "DifficultyLevel")
                        .WithMany()
                        .HasForeignKey("DifficultyLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlan", "ExamPlan")
                        .WithMany("Distributions")
                        .HasForeignKey("ExamPlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedManagerRole");

                    b.Navigation("DifficultyLevel");

                    b.Navigation("ExamPlan");
                });

            modelBuilder.Entity("QBCA.Models.ExamQuestion", b =>
                {
                    b.HasOne("QBCA.Models.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlan", "ExamPlan")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamPlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ExamPlan");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QBCA.Models.ExamReview", b =>
                {
                    b.HasOne("QBCA.Models.ExamQuestion", "ExamQuestion")
                        .WithMany("ExamReviews")
                        .HasForeignKey("ExamQuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "Reviewer")
                        .WithMany("ExamReviews")
                        .HasForeignKey("ReviewerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamQuestion");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("QBCA.Models.Login", b =>
                {
                    b.HasOne("QBCA.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QBCA.Models.Notification", b =>
                {
                    b.HasOne("QBCA.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QBCA.Models.Question", b =>
                {
                    b.HasOne("QBCA.Models.CLO", "CLO")
                        .WithMany("Questions")
                        .HasForeignKey("CLOID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "Creator")
                        .WithMany("QuestionsCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.DifficultyLevel", "DifficultyLevel")
                        .WithMany("Questions")
                        .HasForeignKey("DifficultyLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlanDistribution", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamPlanDistributionDistributionID");

                    b.HasOne("QBCA.Models.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.SubmissionTable", "SubmissionTable")
                        .WithMany("Questions")
                        .HasForeignKey("SubmissionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CLO");

                    b.Navigation("Creator");

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Subject");

                    b.Navigation("SubmissionTable");
                });

            modelBuilder.Entity("QBCA.Models.ReviewExam", b =>
                {
                    b.HasOne("QBCA.Models.ExamPlanDistribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlan", "ExamPlan")
                        .WithMany()
                        .HasForeignKey("ExamPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribution");

                    b.Navigation("ExamPlan");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("QBCA.Models.Subject", b =>
                {
                    b.HasOne("QBCA.Models.User", "Creator")
                        .WithMany("SubjectsCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("QBCA.Models.SubmissionApproval", b =>
                {
                    b.HasOne("QBCA.Models.User", "Approver")
                        .WithMany("SubmissionApprovals")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QBCA.Models.AssignedPlan", "AssignedPlan")
                        .WithMany()
                        .HasForeignKey("AssignedPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QBCA.Models.SubmissionTable", "SubmissionTable")
                        .WithMany("SubmissionApprovals")
                        .HasForeignKey("SubmissionTableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("AssignedPlan");

                    b.Navigation("SubmissionTable");
                });

            modelBuilder.Entity("QBCA.Models.SubmissionTable", b =>
                {
                    b.HasOne("QBCA.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QBCA.Models.User", "Creator")
                        .WithMany("SubmissionTablesCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlan", "ExamPlan")
                        .WithMany("SubmissionTables")
                        .HasForeignKey("PlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("ExamPlan");
                });

            modelBuilder.Entity("QBCA.Models.TaskAssignment", b =>
                {
                    b.HasOne("QBCA.Models.User", "Assigner")
                        .WithMany("TaskAssignmentsAssigned")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.User", "Assignee")
                        .WithMany("TaskAssignmentsReceived")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlanDistribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QBCA.Models.ExamPlanDistribution", null)
                        .WithMany("TaskAssignments")
                        .HasForeignKey("ExamPlanDistributionDistributionID");

                    b.HasOne("QBCA.Models.ExamPlan", "ExamPlan")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("ExamPlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Assigner");

                    b.Navigation("Distribution");

                    b.Navigation("ExamPlan");
                });

            modelBuilder.Entity("QBCA.Models.User", b =>
                {
                    b.HasOne("QBCA.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.MockExam", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Feedbacks");

                    b.Navigation("Questions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CNPM_QBCA.Models.MockFeedback", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("QBCA.Models.CLO", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QBCA.Models.DifficultyLevel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QBCA.Models.Exam", b =>
                {
                    b.Navigation("ApproveTasks");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("QBCA.Models.ExamPlan", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("ExamQuestions");

                    b.Navigation("SubmissionTables");

                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("QBCA.Models.ExamPlanDistribution", b =>
                {
                    b.Navigation("Exam")
                        .IsRequired();

                    b.Navigation("Questions");

                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("QBCA.Models.ExamQuestion", b =>
                {
                    b.Navigation("ExamReviews");
                });

            modelBuilder.Entity("QBCA.Models.ExamReview", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("QBCA.Models.Question", b =>
                {
                    b.Navigation("DuplicateCheckResults");

                    b.Navigation("ExamQuestions");

                    b.Navigation("SimilarQuestions");
                });

            modelBuilder.Entity("QBCA.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("QBCA.Models.Subject", b =>
                {
                    b.Navigation("CLOs");

                    b.Navigation("DifficultyLevels");

                    b.Navigation("ExamPlans");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QBCA.Models.SubmissionTable", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SubmissionApprovals");
                });

            modelBuilder.Entity("QBCA.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("ExamPlansCreated");

                    b.Navigation("ExamReviews");

                    b.Navigation("Logins");

                    b.Navigation("Notifications");

                    b.Navigation("QuestionsCreated");

                    b.Navigation("SubjectsCreated");

                    b.Navigation("SubmissionApprovals");

                    b.Navigation("SubmissionTablesCreated");

                    b.Navigation("TaskAssignmentsAssigned");

                    b.Navigation("TaskAssignmentsReceived");

                    b.Navigation("TasksAssigned");

                    b.Navigation("TasksCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
